#!/usr/bin/env python3
"""Generate Phase 2 sweep config from top-K Phase 1 results.

Reads metrics.json files from a Phase 1 output dir, picks the top K by val_loss,
and writes a Phase 2 YAML that re-runs those variants at 30k steps.

Usage:
  uv run python scripts/generate_phase2_config.py \
      --phase1-dir runs/local_pull/sweep2_phase1 \
      --phase1-config configs/sweep2_phase1_arch.yaml \
      --output configs/sweep2_phase2_finals.yaml \
      --top-k 5
"""

from __future__ import annotations

import argparse
import json
from copy import deepcopy
from pathlib import Path

import yaml


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--phase1-dir", type=Path, required=True, help="Dir with p1_*.metrics.json files")
    parser.add_argument(
        "--phase1-config", type=Path, required=True, help="Original Phase 1 YAML to copy variant defs from"
    )
    parser.add_argument("--output", type=Path, required=True, help="Phase 2 YAML output path")
    parser.add_argument("--top-k", type=int, default=5)
    parser.add_argument("--steps", type=int, default=30000, help="Phase 2 step count")
    parser.add_argument("--validation-interval", type=int, default=2500)
    parser.add_argument("--validation-steps", type=int, default=200)
    args = parser.parse_args()

    # Load Phase 1 metrics + variant defs
    metrics: list[tuple[str, float]] = []
    for path in sorted(args.phase1_dir.glob("*.metrics.json")):
        try:
            data = json.loads(path.read_text())
        except json.JSONDecodeError:
            continue
        name = path.stem.replace(".metrics", "")
        val_loss = data.get("val_loss")
        if val_loss is None:
            continue
        metrics.append((name, float(val_loss)))

    if not metrics:
        raise SystemExit(f"No metrics found in {args.phase1_dir}")

    metrics.sort(key=lambda r: r[1])
    top = metrics[: args.top_k]
    print(f"Top {len(top)} Phase 1 variants by val_loss:")
    for name, loss in top:
        print(f"  {name}: val_loss={loss:.4f}")

    # Load Phase 1 config
    with args.phase1_config.open() as f:
        phase1 = yaml.safe_load(f)
    p1_variants = {v["name"]: v for v in phase1["sweep"]["variants"]}

    # Build Phase 2 config: same defaults but more steps, just the top variants renamed p2_
    p2 = deepcopy(phase1)
    p2["sweep"]["name"] = "sweep2_phase2_finals"
    p2["sweep"]["defaults"]["training"]["steps"] = args.steps
    p2["sweep"]["defaults"]["training"]["validation_interval"] = args.validation_interval
    p2["sweep"]["defaults"]["training"]["validation_steps"] = args.validation_steps
    p2["sweep"]["defaults"]["training"]["save_checkpoints"] = True
    p2["sweep"]["defaults"]["training"]["checkpoint_interval"] = 5000

    p2_variants = []
    for name, _ in top:
        if name not in p1_variants:
            print(f"WARNING: variant {name} not in Phase 1 config, skipping")
            continue
        v = deepcopy(p1_variants[name])
        v["name"] = name.replace("p1_", "p2_") + "_30k"
        p2_variants.append(v)
    p2["sweep"]["variants"] = p2_variants

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w") as f:
        f.write("# Sweep 2 — Phase 2: Top-K from Phase 1 at 30k steps\n")
        f.write("# AUTO-GENERATED by scripts/generate_phase2_config.py\n")
        f.write("\n")
        yaml.safe_dump(p2, f, sort_keys=False, default_flow_style=False)
    print(f"\nWrote Phase 2 config to {args.output} ({len(p2_variants)} variants)")


if __name__ == "__main__":
    main()
